//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "issuekind")]
pub enum Issuekind {
    #[sea_orm(string_value = "Improvement")]
    Improvement,
    #[sea_orm(string_value = "Issue")]
    Issue,
}
